import { IPin } from "../components/Pin";

export const pinsData: IPin[] = [
    {
        id: "1",
        title: "React",
        url: "https://picsum.photos/id/10/367/267",
        author: "Jordan Walke",
        commentsCount: 0,
        date: 100,
        likesCount: 3,
        dislikesCount: -1,
    },
    {
        id: "2",
        title: "React",
        url: "https://picsum.photos/id/1003/367/267",
        author: "Jordan Kepler",
        commentsCount: 0,
        date: 2,
        likesCount: 4,
        dislikesCount: -3,
    },
    {
        id: "3",
        title: "React",
        url: "https://picsum.photos/id/101/367/269",
        author: "Josue Walke",
        commentsCount: 0,
        date: 200,
        likesCount: 7,
        dislikesCount: -2,
    },
    {
        id: "4",
        title: "Angular",
        url: "https://picsum.photos/id/890/367/270",
        author: "Michael Wolf",
        commentsCount: 0,
        date: 300,
        likesCount: 4,
        dislikesCount: -3,
    },
    {
        id: "5",
        title: "React",
        url: "https://picsum.photos/id/99/367/267",
        author: "Jordan Walke",
        commentsCount: 0,
        date: 400,
        likesCount: 8,
        dislikesCount: -2,
    },
    {
        id: "6",
        title: "Ballons",
        url: "https://picsum.photos/id/56/367/267",
        author: "Jordan Kepler",
        commentsCount: 0,
        date: 500,
        likesCount: 12,
        dislikesCount: -3,
    },
    {
        id: "7",
        title: "React",
        url: "https://picsum.photos/id/234/367/269",
        author: "Josue Walke",
        commentsCount: 0,
        date: 600,
        likesCount: -5,
        dislikesCount: -1,
    },
    {
        id: "8",
        title: "React",
        url: "https://picsum.photos/id/456/367/270",
        author: "Michael Wolf",
        commentsCount: 0,
        date: 700,
        likesCount: 6,
        dislikesCount: 1,
    },
    {
        id: "8",
        title: "React",
        url: "https://picsum.photos/id/456/367/270",
        author: "Michael Wolf",
        commentsCount: 0,
        date: 800,
        likesCount: 6,
        dislikesCount: 1,
    },
    {
        id: "8",
        title: "React",
        url: "https://picsum.photos/id/12/367/270",
        author: "Michael Wolf",
        commentsCount: 0,
        date: 900,
        likesCount: 6,
        dislikesCount: 1,
    },
    {
        id: "8",
        title: "React",
        url: "https://picsum.photos/id/15/367/270",
        author: "Michael Wolf",
        commentsCount: 0,
        date: 1000,
        likesCount: 6,
        dislikesCount: 1,
    },
    {
        id: "8",
        title: "React",
        url: "https://picsum.photos/id/16/367/270",
        author: "Michael Wolf",
        commentsCount: 0,
        date: 1100,
        likesCount: 6,
        dislikesCount: 1,
    },
];
